# Generated by Django 5.0.3 on 2024-03-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_brinquedos_delete_binquedos'),
    ]

    operations = [
        migrations.AddField(
            model_name='brinquedos',
            name='valor',
            field=models.IntegerField(default=0.0, max_length=10),
        ),
    ]
