# Generated by Django 5.0.3 on 2024-03-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_brinquedos_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedos',
            name='valor',
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
