# Generated by Django 5.0.3 on 2024-03-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_brinquedos_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='brinquedos',
            name='descricao',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
