# Generated by Django 5.0.3 on 2024-03-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_brinquedos_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedos',
            name='descricao',
            field=models.CharField(default='', max_length=200),
        ),
    ]
