# Generated by Django 5.0.3 on 2024-03-17 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_contatos_quemsomos'),
    ]

    operations = [
        migrations.AddField(
            model_name='brinquedos',
            name='categoria',
            field=models.CharField(choices=[('INFLAVEL', 'Infável'), ('CAMAELASTICA', 'Cama elastica'), ('MESAS', 'Mesas'), ('PISCINABOLINHAS', 'Piscina de bolinhas')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='brinquedos',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='brinquedos',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brinquedos',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
