# Generated by Django 5.0.3 on 2024-03-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_brinquedos_categoria_brinquedos_data_fotografia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='categoria',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('GMAIL', 'G-mail')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contatos',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
