# Generated by Django 5.0.3 on 2024-03-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_alter_brinquedos_descricao_alter_quemsomos_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quemsomos',
            name='titulo',
            field=models.CharField(default='titulo', max_length=6),
        ),
    ]
