# Generated by Django 5.0.3 on 2024-03-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_alter_quemsomos_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatos',
            name='categoria',
        ),
    ]
