# Generated by Django 5.0.3 on 2024-03-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_remove_contatos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='numero',
            field=models.IntegerField(default=None, max_length=11),
        ),
    ]
