# Generated by Django 5.0.3 on 2024-03-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_alter_contatos_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brinquedos',
            old_name='data_fotografia',
            new_name='data_cadastro',
        ),
        migrations.AlterField(
            model_name='contatos',
            name='numero',
            field=models.IntegerField(default=None),
        ),
    ]
