# Generated by Django 5.0.3 on 2024-03-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_rename_data_fotografia_brinquedos_data_cadastro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListandoFotosDiversas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='brinquedos',
            name='descricao',
            field=models.TextField(default='', max_length=500),
        ),
    ]
