# Generated by Django 5.0.3 on 2024-03-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_fotosdiversas_delete_listandofotosdiversas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotosdiversas',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/<django.db.models.query_utils.DeferredAttribute object at 0x000001FFE84164E0>'),
        ),
    ]
