# Generated by Django 5.0.3 on 2024-03-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0019_alter_fotosdiversas_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotosdiversas',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
