# Generated by Django 5.0.3 on 2024-03-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0020_alter_fotosdiversas_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotosdiversas',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos_diversas/%Y/%m/%d/'),
        ),
    ]
