# Generated by Django 5.0.3 on 2024-03-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0021_alter_fotosdiversas_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedos',
            name='categoria',
            field=models.CharField(choices=[('INFLAVEL', 'Infável'), ('CAMAELASTICA', 'Cama elastica'), ('MESAS', 'Mesas'), ('ELETRONICOS', 'Eletrônicos'), ('PISCINABOLINHAS', 'Piscina de bolinhas')], default='', max_length=100),
        ),
    ]
